=== rschleitzer/Scaly/test.dtd
<!-- Scaly Test DTD (SGML) -->
<!-- Literate testing elements for Scaly documentation -->

<!ELEMENT category - O (tests+)>
<!ATTLIST category
    xml:id      ID          #IMPLIED
    title       CDATA       #IMPLIED
>

<!ELEMENT tests - O (test+)>
<!ATTLIST tests
    xml:id      ID          #IMPLIED
    title       CDATA       #IMPLIED
>

<!ELEMENT test - O (input, expect, description?)>
<!ATTLIST test
    xml:id      ID          #IMPLIED
    skip        (true|false) false
>

<!ELEMENT input - O (#PCDATA)>
<!ELEMENT expect - O (#PCDATA)>
<!ELEMENT description - O (#PCDATA)>

=== rschleitzer/Scaly/tests.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE category SYSTEM "test.dtd">
<category xml:id="literals" title="Literal Expressions">

  <tests xml:id="boolean-literals" title="Boolean Literals">
    <test xml:id="bool-true">
      <input>true</input>
      <expect>true</expect>
    </test>
    <test xml:id="bool-false">
      <input>false</input>
      <expect>false</expect>
    </test>
  </tests>

  <tests xml:id="integer-literals" title="Integer Literals">
    <test xml:id="int-positive">
      <input>42</input>
      <expect>42</expect>
    </test>
    <test xml:id="int-zero">
      <input>0</input>
      <expect>0</expect>
    </test>
    <test xml:id="int-negative">
      <input>-7</input>
      <expect>-7</expect>
    </test>
  </tests>

  <tests xml:id="hex-literals" title="Hexadecimal Literals">
    <test xml:id="hex-ff">
      <input>0xFF</input>
      <expect>255</expect>
    </test>
    <test xml:id="hex-1a">
      <input>0x1A</input>
      <expect>26</expect>
    </test>
    <test xml:id="hex-zero">
      <input>0x0</input>
      <expect>0</expect>
    </test>
  </tests>

  <tests xml:id="float-literals" title="Floating-Point Literals">
    <test xml:id="float-pi">
      <input>3.14</input>
      <expect>3.14</expect>
    </test>
    <test xml:id="float-two">
      <input>2.0</input>
      <expect>2</expect>
    </test>
    <test xml:id="float-half">
      <input>0.5</input>
      <expect>0.5</expect>
    </test>
  </tests>

  <tests xml:id="string-literals" title="String Literals">
    <test xml:id="string-hello">
      <input>"hello"</input>
      <expect>"hello"</expect>
    </test>
    <test xml:id="string-greeting">
      <input>"Hello, World!"</input>
      <expect>"Hello, World!"</expect>
    </test>
    <test xml:id="string-empty">
      <input>""</input>
      <expect>""</expect>
    </test>
    <test xml:id="string-tab">
      <input>"tab\there"</input>
      <expect>"tab\there"</expect>
    </test>
    <test xml:id="string-escaped-quotes">
      <input>"say \"hi\""</input>
      <expect>"say \"hi\""</expect>
    </test>
  </tests>

  <tests xml:id="character-literals" title="Character Literals">
    <test xml:id="char-a">
      <input>`a`</input>
      <expect>"a"</expect>
    </test>
    <test xml:id="char-z">
      <input>`Z`</input>
      <expect>"Z"</expect>
    </test>
  </tests>

</category>
