=== rschleitzer/Scaly/packages/scaly/scaly/compiler/grammar.dtd
<!ELEMENT grammar - - (syntax+, keyword*, punctuation*)>
  <!ATTLIST grammar
    name        CDATA                               #IMPLIED
  >
  
  <!ELEMENT syntax - O (content)*>
  <!ATTLIST syntax
    id          ID                                  #REQUIRED
    abstract    (abstract|concrete)                 concrete
    multiple    (yes|no)                            no
  >

  <!ELEMENT content - O EMPTY>
  <!ATTLIST content
    type        (syntax|keyword|punctuation|
                  colon|semicolon|identifier|
                  attribute|literal|eof)            syntax
    link        IDREF                               #IMPLIED
    property    CDATA                               #IMPLIED
    multiple    (yes|no)                            no
    optional    (yes|no)                            no
  >

  <!ELEMENT keyword - O EMPTY>
  <!ATTLIST keyword
    id          ID                                  #REQUIRED
  >

  <!ELEMENT punctuation - O EMPTY>
  <!ATTLIST punctuation
    id          ID                                  #REQUIRED
    value       CDATA                               #REQUIRED
  >

=== rschleitzer/Scaly/packages/scaly/scaly/compiler/scaly.xml
<?xml version="1.0"?>
<!DOCTYPE grammar SYSTEM "grammar.dtd">
<grammar>
  <syntax id="Program">
    <content link="File" property="file"/>
    <content link="Statement" property="statements" multiple="multiple" optional="optional"/>
  </syntax>
  <syntax id="File">
    <content link="Package" property="packages" multiple="multiple" optional="optional"/>
    <content link="Use" property="uses" multiple="multiple" optional="optional"/>
    <content link="Declaration" property="declarations" multiple="multiple" optional="optional"/>
  </syntax>
  <syntax id="Declaration" multiple="multiple">
    <content link="Symbol" property="symbol"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Symbol" abstract="abstract">
    <content link="Private"/>
    <content link="Definition"/>
    <content link="Function"/>
    <content link="Operator"/>
    <content link="Trait"/>
    <content link="Macro"/>
    <content link="Module"/>
  </syntax>
  <syntax id="Private">
    <content link="private"/>
    <content link="Export" property="export_"/>
  </syntax>
  <syntax id="Export" abstract="abstract">
    <content link="Definition"/>
    <content link="Function"/>
    <content link="Operator"/>
    <content link="Trait"/>
    <content link="Module"/>
  </syntax>
  <syntax id="Member" multiple="multiple">
    <content link="Constituent" property="constituent"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Constituent" abstract="abstract">
    <content link="Definition"/>
    <content link="Function"/>
    <content link="Procedure"/>
    <content link="Operator"/>
    <content link="Implement"/>
    <content link="Trait"/>
    <content link="Macro"/>
    <content link="Module"/>
  </syntax>
  <syntax id="Definition">
    <content link="define"/>
    <content type="identifier" property="name"/>
    <content link="GenericParameters" property="parameters" optional="optional"/>
    <content type="colon" optional="optional"/>
    <content link="Attribute" property="attributes" multiple="multiple" optional="optional"/>
    <content link="Concept" property="concept_"/>
  </syntax>
  <syntax id="GenericParameters">
    <content link="left_bracket"/>
    <content link="GenericParameter" property="parameters" multiple="multiple"/>
    <content link="right_bracket"/>
  </syntax>
  <syntax id="GenericParameter" multiple="multiple">
    <content type="identifier" property="name"/>
    <content link="Attribute" property="attributes" multiple="multiple" optional="optional"/>
    <content link="comma" optional="optional"/>
  </syntax>
  <syntax id="Concept" abstract="abstract">
    <content link="Class"/>
    <content link="Namespace"/>
    <content link="Union"/>
    <content link="Constant"/>
    <content link="Delegate"/>
    <content link="Intrinsic"/>
  </syntax>
  <syntax id="Class">
    <content link="Structure" property="structure"/>
    <content type="colon" optional="optional"/>
    <content link="Body" property="body" optional="optional"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Body">
    <content link="left_curly"/>
    <content link="Use" property="uses" multiple="multiple" optional="optional"/>
    <content link="Init" property="inits" multiple="multiple" optional="optional"/>
    <content link="DeInit" property="deInit" optional="optional"/>
    <content link="Member" property="members" multiple="multiple" optional="optional"/>
    <content link="right_curly"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Namespace">
    <content link="left_curly"/>
    <content link="Use" property="uses" multiple="multiple" optional="optional"/>
    <content link="Declaration" property="declarations" multiple="multiple" optional="optional"/>
    <content link="right_curly"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Union">
    <content link="union"/>
    <content type="colon" optional="optional"/>
    <content link="left_paren"/>
    <content link="Variant" property="variants" multiple="multiple"/>
    <content link="right_paren"/>
    <content type="colon" optional="optional"/>
    <content link="Body" property="body" optional="optional"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Variant" multiple="multiple">
    <content type="identifier" property="name"/>
    <content link="Attribute" property="attributes" multiple="multiple" optional="optional"/>
    <content link="TypeAnnotation" property="annotation" optional="optional"/>
    <content link="comma" optional="optional"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Constant">
    <content link="Type" property="type"/>
    <content link="Operand" property="operation" multiple="multiple" optional="optional"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Delegate">
    <content link="delegate"/>
    <content link="ParameterSet" property="parameters" optional="optional"/>
    <content link="Attribute" property="attributes" multiple="multiple" optional="optional"/>
    <content link="Returns" property="result" optional="optional"/>
    <content link="Throws" property="error" optional="optional"/>
  </syntax>
  <syntax id="GenericArguments">
    <content link="left_bracket"/>
    <content link="GenericArgument" property="generics" multiple="multiple" optional="optional"/>
    <content link="right_bracket"/>
  </syntax>
  <syntax id="GenericArgument" multiple="multiple">
    <content link="Type" property="type"/>
    <content link="comma" optional="optional"/>
  </syntax>
  <syntax id="Optional">
    <content link="question"/>
  </syntax>
  <syntax id="ParameterSet" abstract="abstract">
    <content link="Parameters"/>
    <content link="Type"/>
  </syntax>
  <syntax id="Parameters">
    <content link="left_paren"/>
    <content link="Item" property="items" multiple="multiple" optional="optional"/>
    <content link="right_paren"/>
  </syntax>
  <syntax id="Item" multiple="multiple">
    <content type="identifier" property="name"/>
    <content link="TypeAnnotation" property="annotation" optional="optional"/>
    <content link="comma" optional="optional"/>
    <content type="colon" optional="optional"/>
    <content link="Attribute" property="attributes" multiple="multiple" optional="optional"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Returns">
    <content link="returns"/>
    <content link="Type" property="type"/>
    <content link="Attribute" property="attributes" multiple="multiple" optional="optional"/>
  </syntax>
  <syntax id="Throws">
    <content link="throws"/>
    <content link="Type" property="type"/>
    <content link="Attribute" property="attributes" multiple="multiple" optional="optional"/>
  </syntax>
  <syntax id="Use" multiple="multiple">
    <content link="use"/>
    <content link="Name" property="name"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Implement">
    <content link="implement"/>
    <content link="Type" property="type"/>
    <content link="Attribute" property="attributes" multiple="multiple" optional="optional"/>
    <content type="colon" optional="optional"/>
    <content link="left_curly"/>
    <content link="Use" property="uses" multiple="multiple" optional="optional"/>
    <content link="Method" property="methods" multiple="multiple" optional="optional"/>
    <content link="right_curly"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Trait">
    <content link="trait"/>
    <content link="Name" property="name"/>
    <content link="Extends" property="extension" optional="optional"/>
    <content link="Attribute" property="attributes" multiple="multiple" optional="optional"/>
    <content link="left_curly"/>
    <content link="Use" property="uses" multiple="multiple" optional="optional"/>
    <content link="Method" property="functions" multiple="multiple" optional="optional"/>
    <content link="right_curly"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Method" abstract="abstract" multiple="multiple">
    <content link="Function"/>
    <content link="Procedure"/>
    <content link="Operator"/>
  </syntax>
  <syntax id="Init" multiple="multiple">
    <content link="init"/>
    <content link="ParameterSet" property="parameters" optional="optional"/>
    <content type="colon" optional="optional"/>
    <content link="Action" property="action"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="DeInit">
    <content link="deinit"/>
    <content type="colon" optional="optional"/>
    <content link="Action" property="action"/>
    <content type="colon" optional="optional"/>
  </syntax>
  <syntax id="Function">
    <content link="function"/>
    <content link="Target" property="target"/>
  </syntax>
  <syntax id="Procedure">
    <content link="procedure"/>
    <content link="Target" property="target"/>
  </syntax>
  <syntax id="Operator">
    <content link="operator"/>
    <content link="Target" property="target"/>
  </syntax>
  <syntax id="Target" abstract="abstract">
    <content link="Named"/>
    <content link="Routine"/>
  </syntax>
  <syntax id="Named">
    <content type="identifier" property="name"/>
    <content link="Routine" property="routine"/>
  </syntax>
  <syntax id="Routine">
    <content link="GenericArguments" property="generics" optional="optional"/>
    <content link="Lifetime" property="lifetime" optional="optional"/>
    <content link="ParameterSet" property="parameters" optional="optional"/>
    <content link="Attribute" property="attributes" multiple="multiple" optional="optional"/>
    <content link="Returns" property="returns_" optional="optional"/>
    <content type="colon" optional="optional"/>
    <content link="Throws" property="throws_" optional="optional"/>
    <content type="colon" optional="optional"/>
